- name: DEMO on filters
  hosts: localhost
  vars:
    NAME: Sivakumar Reddy
    COURSE
  tasks:
  - name: convert into upper case
    debug:
      msg: "Hello {{ NAME | upper }}"

  - name: convert into lower case
    debug:
      msg: "{{ some_variable | default(5) }}"

  # - name: printing undefined variable
  #   debug:
  #     msg: "Course is {{ COURSE | default("DevOps") }}"